{% set version = "2.4.2" %}
{% set sha256 = "a568bfdc4c3797c4c2339158928edc7dcf6fa4a267b08e3cec5121e2078b5bd6" %}

package:
  name: pythreejs
  version: {{ version }}

source:
  fn: pythreejs-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/pythreejs/pythreejs-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - nodejs
    - jupyterlab >=3,<4
  run:
    - python >={{ python_min }}
    - ipydatawidgets
    - ipywidgets >=7,<9
    - numpy
    - traitlets

test:
  requires:
    - python {{ python_min }}
  imports:
    - pythreejs

about:
  home: https://github.com/jupyter-widgets/pythreejs
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Python / ThreeJS bridge utilizing the Jupyter widget infrastructure.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - vidartf
